### ISSUE TITLE
temacs segfaulting

### ISSUE THREAD

**Issue by ghost** [larsbrinkhoff/emacs-16.56#1]
Decided to try it out on RH6.5 (GCC 4) x64 arch.

temacs segfaults instantly when being invoked from cmdline.

```
Temporary breakpoint 1, main (argc=1, argv=0x7fffffffde18) at emacs.c:124
124	  int skip_args = 0;
```

Loadup also fails completely so temacs cannot be used for editing.

**Comment by larsbrinkhoff** [comment]
I don't remember exactly what I did to make it run a year ago.  Do you compile with the -m32 flag?

I think loadup wasn't working.  And of course dumping will fail miserably.

**Comment by ghost** [comment]
I don't have the 32bit libs installed so I compiled it as a 64bit program.  Though my best guess would be the amount of `unsigned` stuff in there that's just making it die right away on 64bit.

**Comment by larsbrinkhoff** [comment]
Right, I vaguely recall that I made no attempt to make it work in 64-bit.  So 32-bit libraries will be needed.

**Comment by ghost** [comment]
No problem, I'll close the issue.
