### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by dodona2** [larsbrinkhoff/emacs-16.56#3]
(cd etc; make)
--> ../etc/etags.c:429: undefined reference to `cfree'

(cd src; make)
--> cc -g -Demacs -DDisplayDebug -w   -c -o process.o process.c
process.c: In function ‘child_sig’:
process.c:1207:14: error: storage size of ‘w’ isn’t known
 1207 |   union wait w;
      |              ^
make: *** [<builtin>: process.o] Error 1

**Comment by hwpplayer1** [comment]
Rather than just building the source code I will read the source code and I will try to write it from scratch for my dojo/training activies Thanks @larsbrinkhoff

**Comment by larsbrinkhoff** [comment]
Hello @dodona2,

I didn't see your issue until now.  I was able to compile a "temacs", but I'm sure there's a lot left to do to make this usable.  It's stll very experimental.
